<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <NoWarn>$(NoWarn);CA1707</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="coverlet.collector" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
  </ItemGroup>
  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\SqlSimCity.Archive\SqlSimCity.Archive.csproj" />
    <ProjectReference Include="..\..\src\SqlSimCity.Archive.Tool\SqlSimCity.Archive.Tool.csproj" />
  </ItemGroup>
  <ItemGroup>
    <None Update="Fixtures\*.ssca" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
