<Project Sdk="Microsoft.NET.Sdk.Web">
  <ItemGroup>
    <ProjectReference Include="..\SqlSimCity.Archive\SqlSimCity.Archive.csproj" />
    <ProjectReference Include="..\SqlSimCity.Domain\SqlSimCity.Domain.csproj" />
    <ProjectReference Include="..\SqlSimCity.Contracts\SqlSimCity.Contracts.csproj" />
    <ProjectReference Include="..\SqlSimCity.Storage\SqlSimCity.Storage.csproj" />
    <ProjectReference Include="..\SqlSimCity.Collection\SqlSimCity.Collection.csproj" />
    <ProjectReference Include="..\SqlSimCity.Edge\SqlSimCity.Edge.csproj" />
    <InternalsVisibleTo Include="SqlSimCity.Api.Tests" />
  </ItemGroup>
  <ItemGroup Condition="Exists('..\..\web\dist')">
    <Content Include="..\..\web\dist\**\*" Link="wwwroot\%(RecursiveDir)%(Filename)%(Extension)" CopyToPublishDirectory="PreserveNewest" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="..\..\LICENSE" Link="legal\LICENSE" CopyToPublishDirectory="PreserveNewest" />
    <Content Include="..\..\NOTICE" Link="legal\NOTICE" CopyToPublishDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
