<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\SqlSimCity.Collection\SqlSimCity.Collection.csproj" />
    <ProjectReference Include="..\SqlSimCity.Contracts\SqlSimCity.Contracts.csproj" />
    <ProjectReference Include="..\SqlSimCity.Domain\SqlSimCity.Domain.csproj" />
  </ItemGroup>
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
</Project>
